name: flingon_assister
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  url_launcher: any
  shared_preferences: any
  archive: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - data/qawHaq.json.bz2

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
    - family: DSCpIqaD
      fonts:
        - asset: assets/fonts/DSC-pIqaD.ttf
    - family: TNGpIqaD
      fonts:
        - asset: assets/fonts/TNG-pIqaD.ttf
    - family: pIqaDqolqoS
      fonts:
        - asset: assets/fonts/pIqaD-qolqoS.ttf
